config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  post '/stories' => 'story#story'
  get '/stories/:id/opponent' => 'story#opponent'
  get '/power' => 'story#power'
  get '/call-friends' => 'story#call_friends'
  get '/help-out' => 'story#help_out'
  get '/reaction' => 'story#reaction'
  get '/opponent-power' => 'story#opponent_power'
  get '/reaction-to-opponent' => 'story#reaction_to_opponent'

  get '/characters' => 'character#index'

  resources :users, :only => [:show, :new, :create, :destroy]

  delete '/sessions' => 'sessions#destroy'

  get  '/login'  => "sessions#new",  as: 'login'
  post '/login'   => "sessions#create"

  get '/api/character' => 'api#character'
  get '/api/characters' => 'api#characters'
  get '/api/outcomes' => 'api#outcomes'
  get '/api/friend-outcomes' => 'api#friend_outcomes'
  get '/api/users' => 'api#users'

end

app/models/character.rb
class Character < ActiveRecord::Base

  before_create do
    self.name = self.name.downcase
  end

  scope :has_power?, ->(power){ where("powers LIKE ?", "%#{power}%")}
  scope :has_friends?, ->(friend){ where("friends LIKE ?", "%#{friend}%")}
  scope :has_enemies?, ->(enemy){ where("enemies LIKE ?", "%#{enemy}%")}
  scope :has_team?, ->(team){ where("team LIKE ?", "%#{team}%")}

end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/reaction.rb
class Reaction < ActiveRecord::Base
end

app/models/story.rb
class Story < ActiveRecord::Base

  before_create :zero_moves

  def add_char_damage!
    self.char_one_damage += 1
    self.save!
  end

  def add_opponent_damage!
    self.char_two_damage += 1
    self.save!
  end

  def winner?
    if self.char_one_damage == 5
      Character.find_by(name: self.character_two)
    elsif self.char_two_damage == 5
      Character.find_by(name: self.character_one)
    else
      "none"
    end
  end

  def zero_moves
    self.char_one_damage = 0
    self.char_two_damage = 0
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, uniqueness: true
  has_many :stories
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def character
    if params[:id]
      character = Character.where({id: params[:id]})
    elsif params[:name]
      character = Character.where({name: params[:name]})
    elsif params[:powers]
      character = Character.has_power?(params[:powers])
    elsif params[:friends]
      character = Character.has_friends?(params[:friends])
    elsif params[:enemies]
      character = Character.has_enemies?(params[:enemies])
    elsif params[:image]
      character = Character.where({image: params[:image]})
    elsif params[:teams]
      character = Character.has_team?(params[:teams])
    else
      character = Character.all
    end
    render json: character
  end

  def characters
    characters = Character.all
    render json: characters
  end

  def outcomes
    outcomes = Outcome.all
    render json: outcomes
  end

  def friend_outcomes
    friends = Friend.all
    render json: friends
  end

  def users
    users = User.all
    render json: users
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception # , if: ->{ binding.pry }
  # protect_from_forgery with: :null_session


  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def authorize
    redirect_to root_path unless current_user
  end

end

app/controllers/character_controller.rb
class CharacterController < ApplicationController

  def index
    render json: Character.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @characters = Character.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by({username: params[:username]})
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

end

app/controllers/story_controller.rb
class StoryController < ApplicationController

  def story
    query = params['query'].downcase
    @character = ComicVine.search_query(query)

    if @character == nil
      render json: @character
    else
      story_data = {
        user_id: current_user.id,
        character_one: @character.name,
      }
      story = Story.create(story_data)
      render json: @character
    end
  end

#REFACTOR NOTE: Pass story_id up with request
  def opponent
    story = current_user.stories.last
    random_opponent = Character.all.sample.name
    story.update_attributes(character_two: random_opponent)
    @opponent = Character.find_by(name: random_opponent)
    render json: @opponent
  end

  def power
    current_char = current_user.stories.last.character_one
    opponent = current_user.stories.last.character_two
    power = Character.find_by({name: current_char}).powers.split(", ").sample.upcase
    power_story = {story: "#{current_char.upcase} uses the power of #{power} against #{opponent.upcase}" }
    story = current_user.stories.last
    render json: {"value" => power_story}
  end

  def call_friends
    current_char = current_user.stories.last.character_one
    team_friends = Character.find_by({name: current_char}).friends.split(", ").sample.upcase
    result = Friend.all.sample.friend
    friend_story = {story: result.gsub('*friends*', "#{team_friends}")}
    story = current_user.stories.last
    render json: {"value" => friend_story}
  end

  def help_out
    power = current_user.powers.split(", ").sample.upcase
    opponent = current_user.stories.last.character_two
    user_story = {story: "#{current_user.username.upcase} joins the fray! #{current_user.username.upcase} uses the power of #{power} against #{opponent.upcase}"}
    story = current_user.stories.last
    render json: {"value" => user_story}
  end

  def reaction
    story = current_user.stories.last
    opponent = current_user.stories.last.character_two
    opponent_image = Character.find_by(name: opponent).image
    rand_reaction = Reaction.all.sample
    reaction_type = rand_reaction.hit_or_miss
    if reaction_type == "hit"
      story.add_opponent_damage!
    end
    damage_status = story.char_two_damage
    outcome = story.winner?
    reaction_story = {story: rand_reaction.reaction.gsub('*char*',"#{opponent.upcase}"), type: reaction_type, damage: damage_status, outcome: outcome, image: opponent_image }
    render json: {"value" => reaction_story}
  end

##OPPONENT ACTIONS###
  def opponent_power
    current_char = current_user.stories.last.character_one
    opponent = current_user.stories.last.character_two
    power = Character.find_by({name: opponent}).powers.split(", ").sample.upcase
    opponent_power_story = {story: "#{opponent.upcase} uses the power of #{power} against #{current_char.upcase}" }

    render json: {"value" => opponent_power_story}
  end

  def reaction_to_opponent
    story = current_user.stories.last
    current_char = current_user.stories.last.character_one
    current_char_image = Character.find_by(name: current_char).image
    rand_reaction = Reaction.all.sample
    reaction_type = rand_reaction.hit_or_miss
    if reaction_type == "hit"
      story.add_char_damage!
    end
    damage_status = story.char_one_damage
    outcome = story.winner?
    opponent_reaction_story = {story: rand_reaction.reaction.gsub('*char*',"#{current_char.upcase}"), type: reaction_type, damage: damage_status, outcome: outcome, image: current_char_image}

    render json: {"value" => opponent_reaction_story}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, except: [:show, :new, :create]

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    if params[:user]
      @user = User.create(user_params)
      render 'home/index'
    else
      @user = User.create(username: params[:username], password: params[:password])
      render 'home/index'
    end
  end

  def destroy
    @user.destroy
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :image, :first_name, :last_name, :powers)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.erb
<!-- necessary to add these to function -->
<script src="/assets/jquery.js"></script>
<script src="/assets/jcarousel.js"></script>
<script src="/assets/jc_control.js"></script>
<script src="/assets/jc_autoscroll.js"></script>
<script src="/assets/jc_pagination.js"></script>
<script src="/assets/jc_scrollintoview.js"></script>


<div class="jcarousel-wrapper">
	<div class="jcarousel">
		<ul>
			<li><img class="carousel-image" src="/assets/carousel/1.png"></li>
			<li><img class="carousel-image" src="/assets/carousel/2.png"></li>
			<li><img class="carousel-image" src="/assets/carousel/3.png"></li>
			<li><img class="carousel-image" src="/assets/carousel/4.png"></li>
			<li></li>
		</ul>
	</div>

	<a href="#" class="jcarousel-control-prev">&lsaquo;</a>
	<a href="#" class="jcarousel-control-next">&rsaquo;</a>

	</p>
</div>


<script>
(function($) {
	$(function() {
		$('.jcarousel').jcarousel();

		$('.jcarousel-control-prev')
		.on('jcarouselcontrol:active', function() {
			$(this).removeClass('inactive');
		})
		.on('jcarouselcontrol:inactive', function() {
			$(this).addClass('inactive');
		})
		.jcarouselControl({
			target: '-=1'
		});

		$('.jcarousel-control-next')
		.on('jcarouselcontrol:active', function() {
			$(this).removeClass('inactive');
		})
		.on('jcarouselcontrol:inactive', function() {
			$(this).addClass('inactive');
		})
		.jcarouselControl({
			target: '+=1'
		});

		$('.jcarousel-pagination')
		.on('jcarouselpagination:active', 'a', function() {
			$(this).addClass('active');
		})
		.on('jcarouselpagination:inactive', 'a', function() {
			$(this).removeClass('active');
		})
		.jcarouselPagination();
	});
})(jQuery);
</script>

app/views/home/_character.html.erb
<div class="container">
 	<div class="row">
		<div id="character-list">
			<h1><%%= name %></h1>
			<img width="50px" height="auto" src="<%%= image %>">
			<p><span>TEAM FRIENDS:</span> <%%= friends %></p>
			<p><span>POWERS:<%%= powers %></span></p>
		</div>
	</div>
</div>
	    

app/views/home/_navigation.html.erb
<div id="navigation">		
	<% if current_user %>
	<div class="nine columns" id="nav-user">
		Hello, <%= link_to current_user.username, user_path(current_user.id) %>
		<img id="avatar" src="<%=current_user.image%>">
	</div>
	<div class="three columns" id="logout">
		<%= form_tag sessions_path, method: 'delete' do %>
		<%= submit_tag 'Logout', id: 'nav-buttons' %>
		<% end %>
	</div>
	<% else %>
	<div class="one-half">
		<%= link_to 'Log In', login_path, id: 'nav-buttons' %>
		<%= link_to 'Sign Up', new_user_path, id: 'nav-buttons' %>
	</div>
	<% end %>
</div>

app/views/home/_opponent.html.erb
<div class="row">
	<div id="opponent" class="four columns">
		<span><p>YOUR OPPONENT: <%%= name.toUpperCase() %></p></span>

		<div class="health-border">
			<div id="opponent-health-meter">
				<%=image_tag("skullbones.png", :class => "health-image")%>
			</div>
		</div><br>

		<img class="character-image" width="175px" height="auto" src="<%%= image %>">
	</div>
</div>

app/views/home/_results.html.erb
<div class="row">
	<div id="results" class="four columns">
		<span><p>YOUR CHARACTER: <%%= name.toUpperCase() %></p></span>

		<div class="health-border">
			<div id="character-health-meter">
				<%=image_tag("skullbones.png", :class => "health-image")%>
			</div>
		</div><br>

		<img class="character-image" width="175px" height="auto" src="<%%= image %>">
	</div>
</div>

app/views/home/_story.html.erb
<div class="row">
	<div id="story-text" class="four columns">
		<center>&#9830; &#9830; &#9830; &#9830;</center>
		<p><%%= story %></p>
	</div>
</div>

app/views/home/_welcome.html.erb
<div id="welcome-image"></div>

<div class="container">
	<div class="row">
		<div id="title">
			<h1>COMIC SMASH UP!</h1>
		</div>
	</div>
	<img id="zap" src="/assets/zap.png">
	<img id="bang" src="/assets/bang.png">
	<img id="pow" src="/assets/pow.png">
</div>
<div id="message">
	<h5>PICK YOUR FAVORITE COMIC BOOK CHARACTER. MAKE YOUR MOVES. WATCH THE BATTLE UNFOLD!</h5>
	<button id="play">CLICK TO PLAY</button>
</div>

app/views/home/_winner.html.erb
<div id="winner-results">
	<p id="winner-name"></p>
	<div id="winner-image"></div>
	<button id="play-again">Play Again?</button>
</div>

app/views/home/index.html.erb
<%if current_user %>
<%else%>
	<div id="welcome">
	<%= render 'home/welcome' %>
	</div>
<%end%>

<div class="container">
	<div class="row">
		<div id="subheader">
			<div class="eight columns">
				<% if current_user %>
					<%= form_tag("/search", method: "get", :id => 'search') do %>
					<%= label_tag("Choose", "CHOOSE YOUR COMIC BOOK CHARACTER") %>
					<%= text_field_tag 'query', '', placeholder: '...Wolverine?', id: 'input' %>
					<%= submit_tag("Go!") %>
	
					<div id='search-error'>
					</div>

					<% end %>
				<% else %>
					<h5>Sign In or Log In To Start</h5>
				<% end %>

			</div>

			<div class="three columns">
				<button class="character-action" id="all-chars">SEE LIST OF PAST CHARACTERS PLAYED</button>
			</div>
		</div>
	</div>

	<div id="game-results">
		<div id="buttons">
			<p id="choose">CHOOSE AN ACTION TO START BUILDING OUT YOUR STORY</p>
			<button class="character-action" id="power-button">Use Power</button>
			<button class="character-action" id="friend-button">Call for Friends!</button>
			<button class="character-action" id="help-out-button">Help Out</button>
		</div>

		<div>
			<%= render 'home/carousel' %>
		</div>

		<div class="row">
			<div id="content" class="twelve columns">

				<div id="chosen-character" class="four columns">
				</div>

				<div id="opponent-character" class="four columns">
				</div>

				<div id="story-results" class="four columns">
				</div>
			</div>
		</div>
	</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Comic SmashUp</title>	

	<%= stylesheet_link_tag    'application', media: 'all'  %>

	<link href='http://fonts.googleapis.com/css?family=Permanent+Marker|Combo' rel='stylesheet' type='text/css'>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width", initial-scale=1, maximum-scale=1>
	
</head>

<body>
	<div class="container">
		<div class="row">
			<header class="twelve columns">
				<div class="six columns">
					<h1><%= link_to "Comic Smash Up!", root_url, id: "title" %></h1>
				</div>
				<div class="six columns">
					<%= render 'home/navigation' %>
				</div>
			</header>
		</div>
	</div>		

	<div id="game-area">

		<%= yield %>

		<ul class="characters">

		<%= render 'home/winner' %>

		</ul>
		<script type='template' id='character-list-item-template'>
		<%= render 'home/character' %>
		</script>

		<!-- 	 home scripts -->
		<script type='template' id='result-template'>
		<%= render 'home/results' %>
		</script>

		<script type='template' id='opponent-template'>
		<%= render 'home/opponent' %>
		</script>

		<script type='template' id='story-template'>
		<%= render 'home/story' %>
		</script>
	</div>
</body>

<%= javascript_include_tag 'application' %>
</html>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="user-info">

      <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= f.label :username %><br>
        <%= f.text_field :username, :placeholder => "username..." %>
      </div>
      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password, :placeholder => "password..." %>
      </div>
      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, :placeholder => "first name..." %>
      </div>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, :placeholder => "last name..." %>
      </div>
      <div class="field">
        <%= f.label :image, "Image (Add as URL)" %><br>
        <%= f.text_field :image, :placeholder => "image..." %>
      </div>
      <div class="field">
        <%= f.label :powers, "Powers (Separate by Commas)" %><br>
        <%= f.text_field :powers, :placeholder => "ex. flying, invisibility..." %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
	<div class="row">
		<div class="user-info">
			<h2>New User</h2>

			<%= render 'form' %>

			<%= link_to 'Back', root_path %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="user-info">
	
			<h1>Welcome, <%=current_user.first_name%></h1>
			<img id="profile" src="<%=current_user.image%>" width="20%" height="auto">
			<p>Name: <%=current_user.first_name%></p>
			<p>Powers: <%=current_user.powers%></p>
			<%= link_to 'PLAY GAME', root_path, id: "profile-play-game" %>
		</div>
	</div>
</div>